import { motion } from 'framer-motion';
import { ArrowRight, BookOpen, ChevronRight, Download, Files, Upload } from 'lucide-react';
import { Link } from 'react-router-dom';

const levels = ['100', '200', '300', '400'];
export function HomePage() {
  return <main className='page-shell'>
    <section className='hero-grid'><div className='relative z-10 max-w-2xl'><motion.p initial={{ opacity:0 }} animate={{ opacity:1 }} className='eyebrow'>A shared digital campus library</motion.p><motion.h1 initial={{ opacity:0,y:16 }} animate={{ opacity:1,y:0 }} transition={{ delay:.1 }} className='hero-title'>Everything you need to <span>learn better.</span></motion.h1><p className='hero-copy'>Lecture slides and past questions, shared freely by NUPS-G students across Ghana. Find your course or make someone’s semester easier.</p><div className='mt-8 flex flex-wrap gap-3'><Link className='primary-button' to='/browse'><BookOpen size={18}/> Explore the library <ArrowRight size={17}/></Link><Link className='secondary-button' to='/upload'><Upload size={17}/> Share a resource</Link></div><div className='mt-11 flex flex-wrap gap-7 text-sm text-slate-600'><span><b className='text-xl text-blue-900'>Open</b><br/>to every student</span><span><b className='text-xl text-blue-900'>Free</b><br/>to use and share</span><span><b className='text-xl text-blue-900'>One place</b><br/>for your courses</span></div></div><div className='hero-orb'><div className='orbit-card first'><Files /><span>Lecture slides</span></div><div className='orbit-card second'><Download /><span>Past questions</span></div><div className='hero-mark'><img src='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStuRUj1mHE_qZLdcIfE7iqb61NyiIUrALhTCy-zYhzBA&s=10' alt='NUPS-G crest' className='h-20 w-20 rounded-full object-cover' /><b>NUPS-G</b><small>RESOURCE HUB</small></div></div></section>
    <section className='section'><div className='section-heading'><div><p className='eyebrow'>Navigate your curriculum</p><h2>Find a resource by your path.</h2><p>Choose your level, then narrow down to the semester and course you need.</p></div><Link to='/browse' className='text-link'>Browse every resource <ArrowRight size={16}/></Link></div><div className='level-grid'>{levels.map((level, i)=><Link key={level} to={`/browse?level=${level}`} className='level-card'><span>Level</span><strong>{level}</strong><p>{i === 0 ? 'Build your foundation' : i === 3 ? 'Finish strong' : 'Keep progressing'}</p><ChevronRight size={18}/></Link>)}</div></section>
    <section className='section callout'><div><p className='eyebrow'>Give back</p><h2>Your notes could be someone’s breakthrough.</h2><p>Upload a slide deck or past question in under a minute. No account needed.</p></div><Link className='primary-button' to='/upload'>Upload a resource <Upload size={17}/></Link></section>
    <footer>© 2026 Piusson · NUPS-G Resource Hub · Learn Together. Share Together. · Contact: <a href='tel:0556188192' className='font-semibold text-blue-700 hover:underline'>055 618 8192</a></footer>
  </main>;
}
